Classifier implementation
jamadaha/P5 pull request #127
Opened 2021-11-12 09:34 UTC by NanaSandberg

Classifier is working and can successfully train and evaluate a model with input defined from the BaseRunConfig file.

2021-11-15 08:02 UTC, kris701 requested changes
Some things need to be looked at, other than the review comments:
* Currently, the Classifier is not even run (should be included in the JANGANQueue)
* The classifier package and all its modules, need to be reloaded in the `JANGANModuleReloader` as well
* Maybe consider using the same DatasetLoader and formatter as the CGAN (just copy for now, another person can make a package for it later). Its just to make sure we have the exact same style of images in both the CGAN and Classifier
* It might be an idea to have a seperate folder, for the training of the Classifier. It would also be an idea to use the DataGenerator before trying to train the Classifier.

2021-11-15 11:28 UTC, NanaSandberg commented on JANGAN/Classifier/CompilerConfigObject.py
> +import tensorflow
Done

2021-11-15 11:30 UTC, NanaSandberg commented on JANGAN/Classifier/DataLoader.py
> +                                                                            labels="inferred",
Done

2021-11-15 11:47 UTC, NanaSandberg commented on JANGAN/Classifier/DataLoader.py
> +    def _cache_dataset(self, dataset: tensorflow.data.Dataset):
Doesn't make a difference so i have just changed them to private

2021-11-15 11:49 UTC, NanaSandberg commented on JANGAN/Classifier/DataLoader.py
> +
????

2021-11-15 12:20 UTC, NanaSandberg commented on JANGAN/JANGAN.py
> +                                        self.cfg.GetBoolValue("Classifier", "Retrain"),
Fixed

2021-11-15 12:35 UTC, NanaSandberg commented on JANGAN/Classifier/__init__.py
> +        self.save_dir =  Path( './training_models')
Done

2021-11-15 12:42 UTC, jamadaha requested changes

2021-11-15 12:42 UTC, jamadaha commented on JANGAN/Classifier/DataLoader.py
> +        self.batch_size = 32
Should this not be a config option?

2021-11-15 12:42 UTC, jamadaha commented on JANGAN/Classifier/__init__.py
> +    def __EvaluateOnRealData(self, data_path: str, validation_split = 0.2, subset = "validaton", seed = 123):
Would it not be an idea to get this seed value from the config?

2021-11-16 08:22 UTC, NanaSandberg commented on JANGAN/Classifier/__init__.py
> +            path.mkdir(parents=True, exist_ok=True)
Done

2021-11-16 09:52 UTC, NanaSandberg commented on JANGAN/Classifier/DataLoader.py
> +        self.batch_size = 32
Done

2021-11-16 09:52 UTC, NanaSandberg commented on JANGAN/Classifier/__init__.py
> +    def __EvaluateOnRealData(self, data_path: str, validation_split = 0.2, subset = "validaton", seed = 123):
Done

2021-11-16 10:00 UTC, NanaSandberg commented on JANGAN/JANGANQueue.py
>              if expDict[key]['MakeCGANDataset'] == "True":
Done

2021-11-16 10:03 UTC, NanaSandberg commented on JANGAN/Classifier/LayerConfigObject.py
> +                    layers.Rescaling(1./255),
Done

2021-11-16 10:21 UTC, NanaSandberg commented on JANGAN/Classifier/LayerConfigObject.py
> +        self.layers.append(layers.Dense(num))
It is now

2021-11-30 11:34 UTC, jamadaha requested changes
Read through, but have not tested

2021-11-30 11:34 UTC, jamadaha commented on JANGAN/Classifier/ClassifierTrainer.py
> +                tf.summary.scalar('Loss', self.__latestLoss, step=epoch)
Would it not be an idea to specify that this is the classifier?

2021-11-30 11:34 UTC, jamadaha commented on JANGAN/Classifier/ClassifierTrainer.py
> +                tf.summary.scalar('Accuracy', self.__latestAccuracy, step=epoch)
Would it not be an idea to specify that this is the classifier?

2021-11-30 11:34 UTC, jamadaha commented on JANGAN/Classifier/LayerDefinition.py
> +                tf.keras.layers.Flatten(input_shape=(28, 28)),
Is there a reason for not having an input layer, as is done in the GAN?

2021-11-30 11:34 UTC, jamadaha commented on JANGAN/Classifier/__init__.py
> +        #    return ckptPath
Any reason for this?

2021-11-30 11:34 UTC, jamadaha commented on JANGAN/ExperimentQueueConfig.ini
> +ProduceCGANLetters = False
Should default not be with this to be true?

2021-11-30 11:34 UTC, jamadaha commented on JANGAN/JANGAN.py
> +    NumerOfClasses = None
Pls fix

2021-11-30 11:36 UTC, kris701 commented on JANGAN/Classifier/LayerDefinition.py
> +                tf.keras.layers.Flatten(input_shape=(28, 28)),
I am not sure, i followed the layer structure of [a tensorflow guide.](https://www.tensorflow.org/tutorials/keras/classification)

2021-11-30 11:36 UTC, kris701 commented on JANGAN/Classifier/__init__.py
> +        #    return ckptPath
The current checkpoint system does not work with multiple checkpoints.
This will be made as an issue after this PR

2021-11-30 11:37 UTC, kris701 commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +IncludeNumbers = True
Simpler to test with
No need to use all 52 classes, just to check if the toolchain is working

2021-11-30 11:37 UTC, kris701 commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +LatestCheckpointPath = "../../Data/BaseExperiment/checkpoints/baseRunConfigRef.txt"
See previous comment about checkpoint

2021-11-30 11:38 UTC, kris701 commented on JANGAN/JANGAN.py
> +    NumerOfClasses = None
Fix what?

2021-11-30 11:38 UTC, kris701 commented on JANGAN/Classifier/ClassifierTrainer.py
> +                tf.summary.scalar('Loss', self.__latestLoss, step=epoch)
I dont know how those names influence the Tensorboard
You are the one that implemented it, do tell what it should be.

2021-11-30 11:38 UTC, kris701 commented on JANGAN/Classifier/ClassifierTrainer.py
> +                tf.summary.scalar('Accuracy', self.__latestAccuracy, step=epoch)
Same as above

2021-11-30 11:42 UTC, jamadaha commented on JANGAN/Classifier/ClassifierTrainer.py
> +                tf.summary.scalar('Loss', self.__latestLoss, step=epoch)
```suggestion
                tf.summary.scalar('ClassifierLoss', self.__latestLoss, step=epoch)
```

2021-11-30 11:42 UTC, jamadaha commented on JANGAN/Classifier/ClassifierTrainer.py
> +                tf.summary.scalar('Accuracy', self.__latestAccuracy, step=epoch)
```suggestion
                tf.summary.scalar('ClassifierAccuracy', self.__latestAccuracy, step=epoch)
```

2021-11-30 11:50 UTC, jamadaha approved these changes

2021-11-30 11:50 UTC, kris701 approved these changes
Seems to work

2021-11-30 11:51 UTC, merged