Auto backup
jamadaha/P5 pull request #131
Opened 2021-11-16 07:39 UTC by HGinnerup

Added {TIMESTAMP} to config, saving the config is still on to do

2021-11-16 08:27 UTC, AnjaLumholtz approved these changes
Beautiful

2021-11-16 08:27 UTC, AnjaLumholtz approved these changes

2021-11-16 08:46 UTC, jamadaha requested changes

2021-11-16 08:46 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +OutputDir = "../../Data/{TIMESTAMP}/FakeOutput/"
Would it be an idea to mention what {TIMESTAMP} does somewhere inside the config?

Also why remove /baseExperiment/?

2021-11-22 11:17 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +# Tokens can be added in the configManager, by default `{TIMESTAMP}` is replaced with a timestamp in the format of YYYYMMDD-hhmmss
```suggestion
# Tokens can be added in the configHelper, by default `{TIMESTAMP}` is replaced with a timestamp in the format of YYYYMMDD-hhmmss
```

2021-11-22 11:23 UTC, AnjaLumholtz reviewed
Bootiful

2021-11-22 11:27 UTC, AnjaLumholtz submitted a review, later dismissed
Just bootiful

2021-11-22 11:54 UTC, jamadaha requested changes

2021-11-22 11:54 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +OutputDir = "../../Data/{TIMESTAMP}/FakeOutput/"
```suggestion
OutputDir = "../../Data/DataExperiment/{TIMESTAMP}/FakeOutput/"
```

2021-11-22 11:54 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +ConfigCopyPath = "../../Data/{TIMESTAMP}/"
```suggestion
ConfigCopyPath = "../../Data/BaseExperiment/{TIMESTAMP}/"
```

2021-11-22 11:54 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +CheckpointPath = "../../Data/{TIMESTAMP}/checkpoints/baseExperiment/"
```suggestion
CheckpointPath = "../../Data/BaseExperiment/{TIMESTAMP}/checkpoints/"
```

2021-11-22 11:54 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +LatestCheckpointPath = "../../Data/checkpoints/baseRunConfigRef.txt"
```suggestion
LatestCheckpointPath = "../../Data/BaseExperiment/checkpoints/baseRunConfigRef.txt"
```

2021-11-22 11:54 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +LogPath = "../../Data/{TIMESTAMP}/Logs/BaseExperiment/"
```suggestion
LogPath = "../../Data/BaseExperiment/{TIMESTAMP}/Logs/"
```

2021-11-22 12:00 UTC, jamadaha approved these changes

2021-11-22 12:03 UTC, merged