Fix memory leak
jamadaha/P5 pull request #145
Opened 2021-11-18 14:16 UTC by AnjaLumholtz

Potential fix

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/ExperimentQueue/TestRunConfig.ini
> +# Do not change values in here for local changes
Is this file intended to be uploaded?

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/ExperimentQueue/TestRun.py
> +# Change functions and methods, to fit the goal of the experiment
Is this file intended to be uploaded?

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/ExperimentQueue/Test2RunConfig.ini
> +# Do not change values in here for local changes
Is this file intended to be uploaded?

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/ExperimentQueue/Test2Run.py
> +# Change functions and methods, to fit the goal of the experiment
Is this file intended to be uploaded?

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/ExperimentQueueConfig.ini
> +TrainCGAN = True
Are these meaningful?

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/CheckMemoryLeak/__init__.py
> +        self.TracemallocPath = '../../Data/TraceMalloc'
Should this be a config option?

2021-11-18 14:21 UTC, jamadaha commented on JANGAN/CheckMemoryLeak/__init__.py
> +        self.TracemallocFile = '/' + time_string + ' tracemalloc.txt'
Could the name be a config option?

2021-11-19 10:19 UTC, jamadaha commented
Tested, seems fine, except for this:
![image](https://user-images.githubusercontent.com/53914190/142606553-3a554339-f2e3-4f40-b038-46e88670c023.png)
Which occurred after running 4 experiments in 1 queue.

2021-11-19 10:37 UTC, HGinnerup requested changes
TraceMalloc looks like something that will add overhead to the whole program.

If it is to remain in the program, maybe make it optional via the config?

2021-11-19 10:37 UTC, HGinnerup commented on JANGAN/CheckMemoryLeak/__init__.py
> +        self.TracemallocPath = '../../Data/TraceMalloc'
I'd think so, if we intend to keep the profiler in the code

2021-11-19 10:37 UTC, HGinnerup commented on JANGAN/CheckMemoryLeak/__init__.py
> +        self.TracemallocFile = '/' + time_string + ' tracemalloc.txt'
Putting it in the config would also remove the need for `time_string` as the config now supports `../../Data/{TIMESTAMP}/TraceMalloc/tracemalloc.txt`

2021-11-22 08:37 UTC, AnjaLumholtz commented
> Tested, seems fine, except for this: ![image](https://user-images.githubusercontent.com/53914190/142606553-3a554339-f2e3-4f40-b038-46e88670c023.png) Which occurred after running 4 experiments in 1 queue.

Fixed

2021-11-22 11:25 UTC, jamadaha approved these changes

2021-11-22 11:35 UTC, HGinnerup requested changes

2021-11-22 11:35 UTC, HGinnerup commented on JANGAN/GlobalConfig.ini
> +RunTraceMalloc = True
Don't enable TraceMalloc on main

2021-11-22 12:03 UTC, HGinnerup approved these changes

2021-11-22 12:03 UTC, merged