Confusion matrix class print
jamadaha/P5 pull request #179
Opened 2021-12-09 09:38 UTC by AnjaLumholtz

2021-12-09 10:57 UTC, kris701 requested changes
This should really not use a .csv file, that has another purpose, just to get labels.
Rather modify or extend some of the modules in the `DatasetLoader` package

2021-12-09 10:57 UTC, kris701 commented on JANGAN/JANGAN.py
> +        for entry in os.listdir(self.cfg.GetStringValue("CGANDATAGENERATOR", "LetterPath")):
Should this not be fore the `CLASSIFIERDATAGENERATOR` category instead?

2021-12-09 10:57 UTC, kris701 commented on JANGAN/ProjectTools/TFLogger.py
> +    def LogConfusionMatrix(self, matrix, step, saveFig, distributionPath):
I am very much not a fan of this using a seperate .csv file, instead of just modifying how the `DatasetLoader` works

2021-12-09 10:57 UTC, kris701 commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +EpochCount = 20
Please dont modify the `BaseRunConfig.ini` file for main

2021-12-10 07:57 UTC, jamadaha approved these changes

2021-12-10 10:41 UTC, jamadaha requested changes

2021-12-10 10:41 UTC, jamadaha commented on JANGAN/DataGenerator/DataExtractor.py
> +            self.Letters = labelHelper.NumberLabels()
Does this not remove the ability to generate both letters and numbers?

2021-12-10 10:41 UTC, jamadaha commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +PurgePreviousData = True
I think this will leave the windows users unhappy

2021-12-10 10:41 UTC, jamadaha commented on JANGAN/ProjectTools/LabelHelper.py
> +    LETTER_RANGE = [*range(ord('a'), ord('z') + 1), *range(ord('A'), ord('Z') + 1)]
This is duplicate, please either remove the old version from dataExtractor or use that

2021-12-10 10:41 UTC, jamadaha commented on JANGAN/ProjectTools/LabelHelper.py
> +    def NumberLabels(self):
Could letterlabels and numberlabels not just be one function with a parameter?

2021-12-10 10:41 UTC, jamadaha commented on JANGAN/ProjectTools/LabelHelper.py
> +    def LetterLabelArray(self):
Could letter label array and number label array not just be one function with a parameter? Or call another function from this?

2021-12-10 10:41 UTC, jamadaha commented on JANGAN/ProjectTools/TFLogger.py
> +        letters = labelHelper.LetterLabelArray()
Is a confusion matrix of numbers possible?

2021-12-10 10:59 UTC, kris701 requested changes
![Confusion matrix](https://user-images.githubusercontent.com/22596587/145563514-e30ac415-dcf3-4668-ace2-a800865553d9.png)
Does not work with only numbers.

2021-12-10 10:59 UTC, kris701 commented on JANGAN/Classifier/ClassifierMLModel.py
> +from tensorflow.python.ops.math_ops import truediv
Do not put these before the `AutoPackageInstaller` calls!
Also include them with `ap.CheckAndInstall(...)`

2021-12-10 10:59 UTC, kris701 commented on JANGAN/ExperimentQueue/BaseRunConfig.ini
> +PrintDistribution = True
Please dont change the baserun config file

2021-12-10 10:59 UTC, kris701 commented on JANGAN/JANGAN.py
> +    def GetClassNames(self):
Is this even used?

2021-12-10 10:59 UTC, kris701 commented on JANGAN/ProjectTools/TFLogger.py
> +import os
Please dont put imports before `AutoPackageInstaller` is used!
Also add them to the CheckAndInstall methods

2021-12-15 07:01 UTC, closed without merging